export const BASE_URL = 'https://api.inclutec.org';
export const API_TOKEN = 'token_here'; // Replace with your actual API token

// Endpoint paths
export const ENDPOINTS = {
    signBySlug: (slug) => `${BASE_URL}/signs/${slug}`,
    allSigns: `${BASE_URL}/signs`,
    signByLanguage: `${BASE_URL}/signs/language/LESCO`,
    speeches: `${BASE_URL}/speech`,
    speechesAll: `${BASE_URL}/speech/all`,
    equivalencias: `${BASE_URL}/equivalenciasTodas`,
    dictionary: `${BASE_URL}/dictionary`,
    health: `${BASE_URL}/health`,
};

// Words to be used in tests
export const TEST_WORDS = [
    'ABREVIATURA',
    'ACTIVIDAD',
    'ADAPTAR',
    'ADECUACION',
    'AHORRAR',
    'ALAJUELA',
    'ALCALÁ',
    'AMSTERDAM',
    'AMÉRICA LATINA',
    'AMÉRICA',
    'APLICAR',
    'APROPIADA',
    'AREA',
    'APOYAR MEJORADO',
    'ASUMIR',
    'PONTIFICIA',
    'POSGRADO',
    'POTENCIAR',
    'PRIVADO MEJORADA',
    'PRESTIGIO',
    'PROBLEMA',
    'PROCESO CORREGIDO',
    'PRODUCTO',
    'PROFESIONAL',
    'PROFESOR',
    'PROPIO',
    'PROGRAMA',
    'PROPONER',
    'PUBLICO MEJORADA',
    'QUEDARSE',
    'CLEI',
    'COMO-IGUAL',
    'COLOMBIA',
    'COMPLETO VALIDAD',
    'COMPUTADORA',
    'COMUNIDAD',
    'CONTINUAR',
    'SEGUIR',
    'CONSTRUCION',
    'CONTROLAR',
    'ADMINISTRAR',
    'COORDINAR',
    'CONSTRUIR',
    'CREAR',
    'CORRECTO',
    'CREAVITIDAD',
    'CYTED',
    'Convenio',
    'Curricular',
    'DECIDIR',
    'DESARROLLAR',
    'DIFUSION',
    'EDUCACION',
    'EL-SALVADOR',
    'EJEMPLO',
    'ELIMINADO',
    'ENFOCAR',
    'ENSEÑAR',
    'ENTORNOS',
    'ESCUELA',
    'EQUIDAD',
    'ESFORZAR',
    'ESTANDAR',
    'ESTRATEGIA-1',
    'ESTRATEGIA',
    'ESTUDIAR',
    'FORMACION',
    'ESTRATEGIA-2',
    'EXCELENTE',
    'EXTENSIÓN',
    'FEDERACIÓN',
    'FLORIDA',
    'Estructura',
    'Estudiante',
    'FORMA',
    'FONDO-PLATA',
    'FRANCIA',
    'FUNCIÓN',
    'Fortalecer',
    'GRADO',
    'GENERACION',
    'GRANDE',
    'GUATEMALA',
    'HABANA',
    'HABER',
    'HAY',
    'TENER',
    'DISPONIBLE',
    'HABILIDADES',
    'HACER-2',
    'HAY-DIFERENTES',
    'HENARES',
    'INCORPORACIÓN',
    'INCLUIR',
    'INFORMAR-2',
    'INGENIERO',
    'INRIA',
    'INSTITUCION',
    'INTERNACIONAL',
    'Influencia',
    'INVESTIGAR',
    'KANSAS',
    'JURIDICOS'
];

// Get a random word from TEST_WORDS
export function getRandomWord() {
    return TEST_WORDS[Math.floor(Math.random() * TEST_WORDS.length)];
}

// Get word by index (useful for controlled testing)
export function getWordByIndex(index) {
    return TEST_WORDS[index % TEST_WORDS.length];
}

// Get total count of available test words
export function getWordCount() {
    return TEST_WORDS.length;
}